FROM --platform=$TARGETPLATFORM nginx AS builder

WORKDIR /app

COPY --exclude=static/images . .

RUN ./quilldrop generate

FROM --platform=$TARGETPLATFORM nginx

COPY --from=builder /app/output /usr/share/nginx/html

EXPOSE 80
